### ISSUE TITLE
App Improvement Feedback

### ISSUE THREAD

**Issue by ArpithaSrinivas5** [sjsucmpe272-fall21/RetinoPathyScanner#2]
Hi Professor,

Good day!

Below is the feedback from today's  demo: 

1) Improve UI and change the image alignment.

2) To display percentage along with predicting the severity levels.

We will implement this and submit in the github by 8- Dec. Thanks for the feedback.

Thanks  and Warm Regards,
Arpitha

**Comment by 97pratyush** [comment]
Both completed
